### ISSUE TITLE
Swedish Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/sv.reactjs.org#1]
## Maintainer List

* @rloqvist
* @machalvan
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@michaellopez) #3 
* [ ] Tutorial (@michaellopez) #5

### Basics

* [x] Hello World (@nsadev) #2 
* [ ] Introducing JSX (@rloqvist) #8 
* [x] Rendering Elements (@lofgrenfredrik) #7 
* [ ] Components and Props (@lofgrenfredrik) #10
* [ ] State and Lifecycle (@NaNdreas) #9
* [ ] Handling Events (@michaellopez) #11
* [ ] Conditional Rendering
* [ ] Lists and Keys
* [ ] Forms (@shwilliam) #12
* [ ] Lifting State Up
* [ ] Composition vs Inheritance
* [ ] Thinking in React (@danielpox) #14

### API Reference

* [ ] React
* [ ] React.Component
* [ ] ReactDOM
* [ ] ReactDOMServer
* [ ] DOM Elements
* [ ] SyntheticEvent
* [ ] Test Utilities
* [ ] Shallow Renderer
* [ ] Test Renderer
* [ ] JS Environment Requirements
* [ ] Glossary

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [ ] tutorial/nav.yml
* [ ] docs/nav.yml

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [ ] Getting Started (@danielpox) #13
* [ ] Add React to a Website (@devpaps)
* [ ] Create a New React App (@danielpox) #15
* [ ] CDN Links

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [ ] Introducing Hooks
  * [ ] Hooks at a Glance
  * [ ] Using the State Hook
  * [ ] Using the Effect Hook
  * [ ] Rules of Hooks
  * [ ] Building Your Own Hooks
  * [ ] Hooks API Reference
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [ ] Fragments
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [ ] APIs and AJAX
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [x] CodeEditor (@michaellopez) #4 
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by tesseralis** [comment]
@rloqvist, @machalvan please use this issue to track your progress and let me know if you have any questions!

**Comment by rloqvist** [comment]
@tesseralis Hello Nat, thank you!

**Comment by tesseralis** [comment]
@rloqvist @machalvan how's it going? Please let me know if you need any help

**Comment by rloqvist** [comment]
@tesseralis Hello, we were initially waiting for more people to join in, but we will start the process of translating with just the two of us! We will be sure to ask if there is ever anything we require help with!

**Comment by nsadev** [comment]
@tesseralis 
Hi there! Would it be welcome to get help with the translations from someone who's quite new at contributing to open source (me) and eager to get started? Can't see that anyone claimed any pages so if the "Hello World" page is still up for grabs I could start out with that. Let me know if that would be ok and also if I'd need to fork any repo before cloning this one.

**Comment by machalvan** [comment]
Hi @nsadev! You are very welcome to help with the translations. I sign you up for the "Hello World" page. No forking is needed, just clone the repo and submit a PR when you are done. I hope you will enjoy the world of open source.

**Comment by nsadev** [comment]
@machalvan Awesome, thank you!

**Comment by nsadev** [comment]
Hello!

Have finished the translation though it's still in a Word-doc since running into problems when trying to get Yarn and Gatsby to play nicely = can't see the site "live" which would be good, easier to see if the text flow is ok that way.

It's the first time I'm using both Yarn and Gatsby (got the lastest stable verisons of both), anyone know what the most common problem is when getting the error "There was an error compiling the html.js component for the development server"?

**Comment by rloqvist** [comment]
Hi @nsadev ! First of all, welcome!

Secondly, I've never experienced that particular error. What is the output of `node --version && yarn --version && gatsby --version`? Make sure you have at least version 8.15.1 (or any of the carbon releases) of node.

If you still have issues, you are more than welcome to submit a PR to my [personal fork](https://github.com/rloqvist/sv.reactjs.org), where I can inspect it live. If it runs and looks good you can then submit a PR to this current fork.

**Comment by nsadev** [comment]
Hi @rloqvist and thank you!

The versions are: v10.15.1, 1.15.2 and 2.5.9 so that shouldn't be the problem.

Could it possibly be that it's "just" a clone (the info from machalvan said I only needed a clone) and not a fork that causes the problem?

Have googled quite a bt and others have encountered the problem but it's been different solutions for most of them.

**Comment by rloqvist** [comment]
A fork and a clone of a repo are exactly the same thing.

I created a branch in this repo called `Hello-World-v1`, you can push to that with `git push -u origin Hello-World-v1`, and if there are no run-time errors we can merge it into the tree :slightly_smiling_face:

**Comment by nsadev** [comment]
Oh lord, well that was a basic I should've known about! 😅🙈

And the newbie problems continue.. When pushing with the command given by @rloqvist I'm getting an error that the permission is denied. Did "checkout -b Hello-World-v1" before adding the translation, was that wrong and not needed?

**Comment by rloqvist** [comment]
If you create your own fork in github and create a pull request from there it will help with the permission error :slightly_smiling_face:

**Comment by nsadev** [comment]
Created my own fork but it didn't help with the permission error.

Found the problem with getting Gatsby up and running, had swedish letters in the folder name. It only shows a blank page but always something.

Could I email the translation to anyone of you instead? You can remove me from the Hello World-page, happy to provide the translation with no credit.

**Comment by rloqvist** [comment]
I believe it is because you are still trying to push to this repo. If you push to your fork we could set up a pull request from there :)

**Comment by nsadev** [comment]
Shoot, read the style guide before asking about contributing and seem to have forgotten about it right away after, sorry! About to correct it all but just to (hopefully) keep errors to the minimum this time, should the title of the page (top of the page below the id) be translated or is that part of all the under the hood stuff as well? 

The problem with viewing the site in a browser seem to be something with Gatsby and looks like a semi-common problem, will look into it a bit more.

**Comment by nsadev** [comment]
Shoot, hade read the style guide before asking to contribute and apparently forgot all about it right away after, sorry! About to correct it all but to (hopefully) keep errors to a minimum this time, should the title of the page (top of content below the id) be translated or is that part of the under the hood stuff as well?

The problem with viewing the site in a browser seem to be a problem in Gatsby that keeps occuring for ppl, will look into it a bit more.

(Sorry if there's duplicate comments, first one didn't show up)

**Comment by nsadev** [comment]
Shoot, hade read the style guide before asking to contribute and apparently forgot all about it right away after, sorry! About to correct it all but to (hopefully) keep errors to a minimum this time, should the title of the page (top of content below the id) be translated or is that part of the under the hood stuff as well?

The problem with viewing the site in a browser seem to be a problem in Gatsby that keeps occuring for ppl, will look into it a bit more.

(Sorry if there are duplicate comments, first one didn't show up)

**Comment by rloqvist** [comment]
I would make it as a rule of thumb that all the "text" the user _sees_ should be translated :slightly_smiling_face:

**Comment by nsadev** [comment]
The title is seen both in the navigation and at the top of the page it self 😏

Didn't translate the title when making the corrections to the Hello Wordl page though. New PR sent, still haven't found the right solution to view the site in browser so please check it (fingers crossed that there are a minimum of errors).

**Comment by rloqvist** [comment]
That is fine, there is both precedence for that and it is supported in the style guide :slightly_smiling_face: please review the feedback on your PR and we will merge it as soon as possible

**Comment by michaellopez** [comment]
@rloqvist @machalvan 

I'm attempting to translate "Home Page". 

I'm not sure how to handle the text inside the components. So I just translated them straight up in the components themselves, let me know if it needs to be done some other way.

Also I'm having a hard time finding this "glossary" that was described in the guidelines, any pointers?

**Comment by michaellopez** [comment]
Also, as part of the Home Page translation I also translated the few words in the `CodeEditor`. See #4

**Comment by michaellopez** [comment]
I'm continuing with the Tutorial page. At around 1200 lines it might take me a few days to finish though. I'm currently around 10 % complete there...

**Comment by lofgrenfredrik** [comment]
@rloqvist @machalvan 

`Rendering Elements` seems unclaimed so I started translating that page. 👍

**Comment by lofgrenfredrik** [comment]
@rloqvist @machalvan 
Taking on the `Components and Props` page next. 👍

**Comment by NaNdreas** [comment]
Hello,

I would love to help on this if you like, it looks like there are not too many contributors yet and progress is on 3% https://isreacttranslatedyet.com/

If you need help I can get busy with the next page in line (Basics: State and Lifecycle). I can also check some of the existing PRs

Good job so far!

**Comment by michaellopez** [comment]
@rloqvist @machalvan I'm doing `Handling Events` page now.

Also note that I've translated `Tutorial` in #5 but it is not marked in this issue as "taken by me".

**Comment by michaellopez** [comment]
@rloqvist @machalvan `Handling Events` is now #11 

I'm doing `Conditional Rendering` page now.

**Comment by shwilliam** [comment]
Hej @rloqvist @machalvan 

Would be happy to help with this! Seems like no one has started translating the `Forms` page yet; will start working on this if that's alright?

**Comment by danielpox** [comment]
Hello @rloqvist and @machalvan 

I would like to translate the `Getting Started` page.

Give me a thumbs up and I’ll get going. 😃

**Comment by danielpox** [comment]
Would it make sense to partially translate `docs/nav.yml` as you translate the various pages? For example, when translating the Getting Started page, one may also update the title in `docs/nav.yml`, instead of waiting until all pages are complete. Sounds fair?

**Comment by danielpox** [comment]
I have translated the `Thinking in React` page: #14

**Comment by danielpox** [comment]
Moving on to translate the `Create a New React App` page.

**Comment by danielpox** [comment]
> 2\. **Please take only one page at a time**.

Does this mean ”translate a page, then wait for it to be reviewed and approved before moving onto translating another page”, or does it simply mean ”don’t start translating another page until you’re done translating the current one”?

Asking for whether or not I can move through a bunch of pages. 😄

**Comment by michaellopez** [comment]
@danielpox I would say the latter. AFAIK it is just so that you don't waste your own time. I have several PRs open, same as my colleague @lofgrenfredrik just go ahead :)

**Comment by danielpox** [comment]
Finished translating the `Create a New React App` page in #15.

**Comment by machalvan** [comment]
Hello @danielpox! Very good job so far. It is fine to work on multiple PRs at the time as long as you feel done with translating the previous page. I will update the progress on the pages you have worked with.

**Comment by NaNdreas** [comment]
Just to let you know I've closed my PR and removed the source fork on "State & lifecycle" due to inactivity, but please feel free to use the content but perhaps with a different author https://github.com/reactjs/sv.reactjs.org/pull/9
Thanks

**Comment by michaellopez** [comment]
Speaking of which, how is the progress on this? We also have the feeling of inactivity that @NaNdreas expresses. What is the official status? What more can we do to move this along? @rloqvist @machalvan

**Comment by rloqvist** [comment]
Admittingly, there have been some inactivity from our side. I'm looking through all the PR in the hope of getting the reviews done today. Tomorrow I will start consolidating all your great suggestions into the glossary.

@NaNdreas I'm sorry to hear that, I will go through your translation and use as much of it as possible.

I apologize for this taking so long, I will try to do better in the future.

**Comment by michaellopez** [comment]
@rloqvist No need to apologise, times of inactivity is totally understandable. Thanks for your efforts 🙇

**Comment by lekoaf** [comment]
So, what's the deal here? Can _anyone_ claim a topic and try their hand at translating this?

Is master up to date? Seems like there is an awful lot of PRs waiting to update the source.

Who's "in charge"?

**Comment by michaellopez** [comment]
@lekoaf well yes, that was the idea. But the "ones in charge" (@rloqvist and @machalvan ) have been inactive for a very long time. Me and @lofgrenfredrik from We ahead have been trying to move this along with numerous PRs. I'm still willing to contribute but I think the repo needs new owners. Not sure if there is any process or if @tesseralis can make something happen...

**Comment by rloqvist** [comment]
There hasn't been much progress since last time and work really picked up for me and @machalvan and thats just how it is sometimes.

@michaellopez We initiated this project in the hopes that more people would join the maintainer team as we went along since it is kind of a large undertaking. If anyone wants to be added to the maintainer list just let me know and I will submit a [pull request](https://github.com/reactjs/reactjs.org-translation#adding-a-maintainer)

**Comment by devpaps** [comment]
Hi guys! I would like to translate the "Add React to a Website". I've forked and are ready to get going. :)

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
